/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * API | v1
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from './fetcher';
export type TaskItemStatus = typeof TaskItemStatus[keyof typeof TaskItemStatus];


export const TaskItemStatus = {
  Todo: 'Todo',
  InProgress: 'InProgress',
  Done: 'Done',
  Cancelled: 'Cancelled',
} as const;

export type TaskItemPriority = typeof TaskItemPriority[keyof typeof TaskItemPriority];


export const TaskItemPriority = {
  Low: 'Low',
  Medium: 'Medium',
  High: 'High',
  Critical: 'Critical',
} as const;

export interface TaskResult {
  id: number;
  title: string;
  /** @nullable */
  description: string | null;
  status: TaskItemStatus;
  priority: TaskItemPriority;
  creatorId: number;
  creatorName: string;
  /** @nullable */
  assignedToId: number | null;
  /** @nullable */
  assignedToName: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ApiSuccessResponseOfListOfTaskResult {
  success?: boolean;
  /** @nullable */
  data: TaskResult[] | null;
}

export interface UserResult {
  id: number;
  name: string;
}

export interface ApiSuccessResponseOfListOfUserResult {
  success?: boolean;
  /** @nullable */
  data: UserResult[] | null;
}

/**
 * @nullable
 */
export type TaskResult2 = {
  id: number;
  title: string;
  /** @nullable */
  description: string | null;
  status: TaskItemStatus;
  priority: TaskItemPriority;
  creatorId: number;
  creatorName: string;
  /** @nullable */
  assignedToId: number | null;
  /** @nullable */
  assignedToName: string | null;
  createdAt: string;
  updatedAt: string;
} | null;

export interface ApiSuccessResponseOfTaskResult {
  success?: boolean;
  data: TaskResult2 | null;
}

export interface CreateTaskRequest {
  title: string;
  /** @nullable */
  description: string | null;
  priority: TaskItemPriority;
  /** @nullable */
  assignedToId: number | null;
  creatorId: number;
}

export type NullableOfTaskItemPriority = typeof NullableOfTaskItemPriority[keyof typeof NullableOfTaskItemPriority] | null;


export const NullableOfTaskItemPriority = {
  Low: 'Low',
  Medium: 'Medium',
  High: 'High',
  Critical: 'Critical',
} as const;

export type NullableOfTaskItemStatus = typeof NullableOfTaskItemStatus[keyof typeof NullableOfTaskItemStatus] | null;


export const NullableOfTaskItemStatus = {
  Todo: 'Todo',
  InProgress: 'InProgress',
  Done: 'Done',
  Cancelled: 'Cancelled',
} as const;

export interface UpdateTaskRequest {
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  status: NullableOfTaskItemStatus | null;
  priority: NullableOfTaskItemPriority | null;
  /** @nullable */
  assignedToId: number | null;
}

export type GetAllTasksParams = {
status?: GetAllTasksStatus;
priority?: GetAllTasksPriority;
assignedToId?: number;
sortBy?: string;
sortDesc?: boolean;
};

export type GetAllTasksStatus = typeof GetAllTasksStatus[keyof typeof GetAllTasksStatus];


export const GetAllTasksStatus = {
  Todo: 'Todo',
  InProgress: 'InProgress',
  Done: 'Done',
  Cancelled: 'Cancelled',
} as const;

export type GetAllTasksPriority = typeof GetAllTasksPriority[keyof typeof GetAllTasksPriority];


export const GetAllTasksPriority = {
  Low: 'Low',
  Medium: 'Medium',
  High: 'High',
  Critical: 'Critical',
} as const;

export type getAllTasksResponse200 = {
  data: ApiSuccessResponseOfListOfTaskResult
  status: 200
}

export type getAllTasksResponseSuccess = (getAllTasksResponse200) & {
  headers: Headers;
};
;

export type getAllTasksResponse = (getAllTasksResponseSuccess)

export const getGetAllTasksUrl = (params?: GetAllTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tasks?${stringifiedParams}` : `/tasks`
}

export const getAllTasks = async (params?: GetAllTasksParams, options?: RequestInit): Promise<getAllTasksResponse> => {

  return customFetch<getAllTasksResponse>(getGetAllTasksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type createTaskResponse201 = {
  data: ApiSuccessResponseOfTaskResult
  status: 201
}

export type createTaskResponseSuccess = (createTaskResponse201) & {
  headers: Headers;
};
;

export type createTaskResponse = (createTaskResponseSuccess)

export const getCreateTaskUrl = () => {




  return `/tasks`
}

export const createTask = async (createTaskRequest: CreateTaskRequest, options?: RequestInit): Promise<createTaskResponse> => {

  return customFetch<createTaskResponse>(getCreateTaskUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTaskRequest)
  }
);}



export type getTaskByIdResponse200 = {
  data: ApiSuccessResponseOfTaskResult
  status: 200
}

export type getTaskByIdResponse404 = {
  data: void
  status: 404
}

export type getTaskByIdResponseSuccess = (getTaskByIdResponse200) & {
  headers: Headers;
};
export type getTaskByIdResponseError = (getTaskByIdResponse404) & {
  headers: Headers;
};

export type getTaskByIdResponse = (getTaskByIdResponseSuccess | getTaskByIdResponseError)

export const getGetTaskByIdUrl = (id: number,) => {




  return `/tasks/${id}`
}

export const getTaskById = async (id: number, options?: RequestInit): Promise<getTaskByIdResponse> => {

  return customFetch<getTaskByIdResponse>(getGetTaskByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type updateTaskResponse200 = {
  data: ApiSuccessResponseOfTaskResult
  status: 200
}

export type updateTaskResponse404 = {
  data: void
  status: 404
}

export type updateTaskResponseSuccess = (updateTaskResponse200) & {
  headers: Headers;
};
export type updateTaskResponseError = (updateTaskResponse404) & {
  headers: Headers;
};

export type updateTaskResponse = (updateTaskResponseSuccess | updateTaskResponseError)

export const getUpdateTaskUrl = (id: number,) => {




  return `/tasks/${id}`
}

export const updateTask = async (id: number,
    updateTaskRequest: UpdateTaskRequest, options?: RequestInit): Promise<updateTaskResponse> => {

  return customFetch<updateTaskResponse>(getUpdateTaskUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateTaskRequest)
  }
);}



export type deleteTaskResponse204 = {
  data: void
  status: 204
}

export type deleteTaskResponse404 = {
  data: void
  status: 404
}

export type deleteTaskResponseSuccess = (deleteTaskResponse204) & {
  headers: Headers;
};
export type deleteTaskResponseError = (deleteTaskResponse404) & {
  headers: Headers;
};

export type deleteTaskResponse = (deleteTaskResponseSuccess | deleteTaskResponseError)

export const getDeleteTaskUrl = (id: number,) => {




  return `/tasks/${id}`
}

export const deleteTask = async (id: number, options?: RequestInit): Promise<deleteTaskResponse> => {

  return customFetch<deleteTaskResponse>(getDeleteTaskUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



export type getAllUsersResponse200 = {
  data: ApiSuccessResponseOfListOfUserResult
  status: 200
}

export type getAllUsersResponseSuccess = (getAllUsersResponse200) & {
  headers: Headers;
};
;

export type getAllUsersResponse = (getAllUsersResponseSuccess)

export const getGetAllUsersUrl = () => {




  return `/users`
}

export const getAllUsers = async ( options?: RequestInit): Promise<getAllUsersResponse> => {

  return customFetch<getAllUsersResponse>(getGetAllUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}
